spring.application.name=admin-command-service

# Database (Command DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/admin_write_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Resilience4j
resilience4j.retry.instances.employeecontroller.base-config=default
resilience4j.circuitbreaker.instances.employeecontroller.base-config=default
