spring.application.name=employee-command-service

# Database (Command DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_write_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Resilience4j
resilience4j.retry.instances.employeecontroller.base-config=default
resilience4j.circuitbreaker.instances.employeecontroller.base-config=default


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

